# Generated by Django 4.2 on 2024-03-30 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 30, 18, 30, 4, 14668)
            ),
        ),
    ]
