# Generated by Django 5.0.2 on 2024-03-10 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_listing_contact_listing_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listing_name',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 10, 20, 2, 55, 744201)),
        ),
    ]
